// import Head from "next/head";
// import Image from "next/image";

import Head from "next/head";
import { ReactNode } from "react";

// import styles from "../styles/Home.module.css";
type Props = {
  title: ReactNode;
};
export default function MetaData({ title }: Props) {
  return (
    <Head>
      <title>{title}&nbsp;-&nbsp;FiFash</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={"/logo/logo.ico"} />
    </Head>
  );
}
